-- Ejercicio 1: Valor medio de la batería de los sensores
-- Ejercicio 2: Sensores con batería por debajo de la media global
-- Ejercicio 3: Mayor temperatura registrada
-- Ejercicio 4: Última lectura registrada
-- Ejercicio 5: lectura registrada más antigua
-- Ejercicio 6: Posibles estados de los sensores (sin repetir) 
-- Ejercicio 7: Cuántos sensores hay en cada estado
-- Ejercicio 8: Qué estado tiene más de 3 sensores en ese estado
